name: GitHub-Profile-3D-Contrib

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user: ${{ github.repository_owner }}
          # Optional: You can change the colors here
          # color_1: '#26A641'
          # color_2: '#41C464'
          # color_3: '#66DC7E'
          # color_4: '#90F29E'

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A .
          git commit -m "generated"
          git push
